server:
  port: 8041

spring:
  application:
    name: feign-consumer
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:120.79.233.86}:${REGISTER_PORT:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:120.79.233.86}:${SENTINEL_DASHBOARD_PORT:8021}

  rabbitmq:
    host: ${RABBIT_MQ_HOST:120.79.233.86}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  zipkin:
    sender:
      type: rabbit
    enabled: true
    base-url: http://120.79.233.86:9411/
  sleuth:
    sampler:
      probability: 1.0
    feign:
      enabled: true
      processor:
        enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

logging:
  level:
    org.springframework.cloud.sleuth: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'