server:
  port: 8022

spring:
  application:
    name: admin
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:120.79.233.86}:${REGISTER_PORT:8848}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:120.79.233.86}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:120.79.233.86}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  #spring boot admin的登陆账号和密码配置
  security:
    user:
      name: admin
      password: 123456
  #通过rabbit MQ将日志发给zipkin
  zipkin:
    enabled: true
    sender:
      type: rabbit
    base-url: http://120.79.233.86:9411/
  sleuth:
    sampler:
      probability: 1.0
#日志相关配置
logging:
  level:
    org.springframework.security: DEBUG
  path: logs/
  file:
    max-size: 1GB


